### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by blurtime** [eonist/HybridCamera#20]
I discovered a memory leak by accident. If you record many videos and cancel all of them right after recording you can see how the memory slowly goes up - until the app crashes: `Message from debugger: Terminated due to memory issue` I've got to go to bed now so I didn't look into anything. Just wanted to open this issue so I don't forget it. I verified it with the "eonist" "master"

**Comment by eonist** [comment]
Im sure there is info about this on SO. Like a .flush() method or something.

**Comment by blurtime** [comment]
Sure, I'll check if I can find a retain cycle. But if I can't identify the problem if you could look over it once since that would be a real bummer if it didn't work for recording more than 4(ish) videos because the rest seems so clean and nice.

**Comment by eonist** [comment]
I have no idea. Could be anything. But it probably has to do with storing the video in memory, and never flushing it. 

Probably an easy fix. I will test the dev branch on my iPhone X now and see.

**Comment by blurtime** [comment]
Alright, thank you! I'm making progress on the flipping :D

**Comment by eonist** [comment]
No memory leak on my iPhone X. Made like 5-6 30 sec videos. memory stayed at around 20mb

**Comment by blurtime** [comment]
That's very odd 🤔But one video didn't cause anything in my case me either. Have you tried recording about 10 videos back to back and always canceling them after they show up?

**Comment by eonist** [comment]
6 videos that are 30sec long and the memory didn't move a needle for me.

**Comment by eonist** [comment]
Try cleaning Xcode

```
My notes when you need to nuke xcode

1. Go to file in xcode -> Workspace settings
2. Click the arrow next to which appears /Users/apple/Library/Developer/Xcode/DerivedData
3. Select the Derived data and move it to Trash.
4. Quite the xcode and reopen it.
5. Clean the project and run again.

Above steps should give you a clean xcode.

```

**Comment by eonist** [comment]
reboot your computer / iphone. Do you have iPhone 6 or newer?

**Comment by blurtime** [comment]
I'll try these steps and get back to you as soon as I've tried it out 👍 Yes, I am testing it on an iPhone 6.

**Comment by eonist** [comment]
I doubt it is this: https://stackoverflow.com/a/25693365/5389500

**Comment by eonist** [comment]
I added a fix for a potential retain cycle crash but it is unrelated to this

**Comment by blurtime** [comment]
I rebooted my iPhone, followed your steps, downloaded the entire project as a `.zip` file again (from the `master` branch). Yet, it still occurs 😶Since I downloaded it, I don't think it is related to those zombie objects (never heard of them)
Have you also tried downloading the project as a zip and trying it out with that `.xcodeproj` file?
I'll check if some other apps of mine also have issues with memory...

**Comment by eonist** [comment]
Is your iPhone full? Or do you have available space?

If it's that. You could flush the temp folder when you go back from video-review.

**Comment by eonist** [comment]
I use GitHub desktop. It doesn't matter if you download or use git. same source.

**Comment by eonist** [comment]
Here is how one can empty temp folder: https://stackoverflow.com/a/37043842/5389500

**Comment by eonist** [comment]
I am on iOS 12.1.4 on my iphoneX tho. I doubt that matters.

**Comment by blurtime** [comment]
I'll see if it's my iPhone first. But I doubt it. After that, I will try implementing your suggestions. I am currently using iOS 12.3.1 I doubt it, too, but can't say for certain...

**Comment by eonist** [comment]
does it happen if you film 2 videos that are say 6 min long each?

**Comment by eonist** [comment]
Its probably in the AVPlayer. See https://stackoverflow.com/questions/24820725/memory-leak-in-ios-avplayer-is-never-deallocated

We use a timer in the record button. Could be similar. 🤷

**Comment by eonist** [comment]
Should probably set some variables to nil here: https://github.com/eonist/HybridCamera/blob/7cf60ac9352245f909fd8111b302f790efe36e48/HybridCamLib/src/process/view/VideoPlayerView.swift#L56 

reference how they do it here:

https://stackoverflow.com/q/24820725/5389500

**Comment by blurtime** [comment]
No, just 6-8 videos that are very short (about 1-2 seconds)... :(
Yeah, probably 🤔Could you maybe try downloading it once as zip and try running it as a separate project? I'll try a couple of things. If they don't work, I'll come back to you. For now, maybe it's better if you focus on more important things :/

**Comment by eonist** [comment]
I added a possible fix memory leak problem in VC.swift onCapture. See dev branch.

**Comment by eonist** [comment]
I guarantee its not a download .zip issue. The hash of the source is the same for downloading or using git. Unless apple differentiate the download from internet file and carries that too Xcode. even if it was that it would be some twilight-zone grade anomaly. Its a lot more likely that in one of the callbacks some .self isn't set to weak and guarded against. since the app crashes. then its probably something like that.

**Comment by eonist** [comment]
This project was rushed together in a week. most of which was researching AVFoundation. Then over time I have refined it and improved bits and pieces. So the deinit of views etc isn't 💯%. I would try: 

- Remove cache files 
- set avplayer to nil 
- add some` [weak self] guard let self = self else { print("💥");return }` in some call-backs near the review-video code.

**Comment by blurtime** [comment]
The thing is I believe that, too. But I can't explain why. I'm even starting to believe it's related to the new Xcode or iOS. I've tried pretty much everything now. It's still occurring - absolutely no idea why. 
I'll try those few last steps. If they aren't working, too, I'll have to see what I'm going to do :/

**Comment by blurtime** [comment]
I don't know what it is. The fix in the develop branch didn't help. One major problem remains that I can't even look at the memory graph for who knows what reason (see picture). I might try creating my own processing controller (from an old project) and see if that works. If you haven't tried just downloading the entire project from `master` maybe do it once just to be 100% sure. Or maybe even give me the project you're using right now as a zip (just the camera part of course) so I can test if it still occurs with your project. Really **no** idea why this is happening (and kind of frustrated at this point...) but since I can't even look at the memory graph I might never know _why_ it's occurring :( I try debugging it but it never finishes. And if I then hit "Continue program execution" I get this error:
<img width="428" alt="Screenshot 2019-07-25 at 00 52 34" src="https://user-images.githubusercontent.com/29407428/61834356-ef430980-ae77-11e9-9b29-742348067fc0.png">
This doesn't occur when I debug it in other projects. There the memory graph pops up after some time. 
Anyway, I don't know how much time I'll have the next couple days. I would really like to contribute more but I've got so little time 😞Very sorry

**Comment by eonist** [comment]
No worries. I deal with problems like this all the time. Its always some small detail. We will figure it out 👍

**Comment by blurtime** [comment]
It doesn't seem to be related to the video player. If I take photos it is occurring, too:
<img width="1440" alt="Screenshot 2019-07-25 at 12 22 33" src="https://user-images.githubusercontent.com/29407428/61867356-4a581900-aed7-11e9-861f-d97e808926ed.png">

**Comment by blurtime** [comment]
**Important update**
After adding weak `self`s essentially everywhere I am now finally able to debug my memory graph 😍 And we are definitely making progress. Filtering for memory leaks didn't give me anything. However, one can easily see that there is a problem. Do you have an idea where these aren't released? 
<img width="1440" alt="Screenshot 2019-07-25 at 13 14 23" src="https://user-images.githubusercontent.com/29407428/61870339-26e49c80-aede-11e9-946c-668bf1acc2d9.png">

**Comment by eonist** [comment]
- Like I said earlier. It has nothing to do with zip or git. This project was made in a week. And I'm sure there are men leaks all over the place. As is always the case when you rush things out. 
- I found a memory leak when taking photos and fixed it.
- I can't reproduce video leak so If that persists for you then I will have to look into that later tonight. 
- Since you spoke about 2 sec videos causing men leak it could have been just photos. as 2 secs basically activates photo, you have to hold the rec button for longer than 2 sec for it to make a video etc.

**Comment by eonist** [comment]
I suggest also researching how to debug mem leaks on youtube. there are many strategies you can take to figure out an issue. And they are often related to changing code. Setting things to nil. Dealocating things, looking into AVFoundation mem leaks other people have struggled with etc. Mem-leaks is common when you deal with video / photo. Sometimes you have to capture things in an old school @autoreleasepool to get things working.

**Comment by eonist** [comment]
I suggest you try the develop branch with the latest commits. And see if that works. also maybe delete the project from your iPhone so your sure you get the new project etc.

**Comment by blurtime** [comment]
I just tried out the `develop` branch. We are definitely making progress! 😍 Namely, I can finally with this project also debug the memory graph. This is seriously a big step. But it is still occurring. I deleted it many times from my iPhone. 

I don't mean that the zipping or git are related to this leak. I just want to know if we are definitely on the same page by using the exact same project since that doesn't seem to be the case (you were e.g. mentioning a timer you were using earlier). I'm currently always working like this (e.g. for a new pull request) so I can try things out right away when I need to: 
1. I download the file `Clone or download` -> `Download ZIP`
2. I put the zip in a folder of my choice and unzip it
3. I open the new folder with the `HybridCamera.xcodeproj` in it 
4. I change the bundle identifier to the same name as a previous project so that I don't reach my limit for free developer accounts (`codes.eon.HybridCam-Develop-`) and me as the Team
5. I run it and try to reproduce the error 
6. Meanwhile, I can finally debug the memory graph now and see the following:
<img width="1440" alt="Screenshot 2019-07-25 at 14 04 24" src="https://user-images.githubusercontent.com/29407428/61873416-42ec3c00-aee6-11e9-98c3-06cf05bf8fe7.png">

I just want to know if you tried reproducing my steps once and if we are definitely on the exact same page because it doesn't seem like that. It doesn't seem to be related to my phone and you were mentioning earlier that you also had a timer, for instance. But I am working with the plain, vanilla project just like someone who discovered this library and wants to try it out once. Do you know what I mean? 😅

Regarding whether those are videos or photos: They were definitely videos (I can see that they are). But regardless of that, taking photos leads to the same picture I posted in this comment: too many `CustomProcessView`s are retained. But I can't put my finger on why yet. I'll try to figure it out. But at least I can debug now! That's a huge step forward in this issue. So thank you for the new commits in the `develop` branch! :)

**Comment by eonist** [comment]
if you try master and take photos. It leads to mem leak. If u try dev. No mem Leaks when taking photos. Because it was fixed. So progress. Let me know if photo men leaks is still a prob for you. And no. There is no timer. That was some other project where we used this lib. And we had a 10 sec timer that stopped the video recording.

**Comment by blurtime** [comment]
But I still get this picture if I take photos: 
<img width="1440" alt="Screenshot 2019-07-25 at 15 21 24" src="https://user-images.githubusercontent.com/29407428/61877795-09b8c980-aef0-11e9-94f4-aee4eef5d8d6.png">
I managed to remove some strong references from the views. One remains though and I highlighted it in the picture.

**Comment by eonist** [comment]
Sure. What I am asking is. Does the memory build up like in master. IN master the memory adds 15mb for each picture. IN dev it doesn't. Sure, there might be views retained etc. But it doesn't build up the memory. You can perfect that issue later. Lets focus on one issue at the time.

**Comment by eonist** [comment]
If you still get video mem leaks. Then you have to add some code in the videoView.deInitiate method. Try to set the avplayer to nil. Try to empty the cache like I mentioned in a previous comment. With code from SO: Once thous are in place I think what your experiencing will go away.

**Comment by blurtime** [comment]
No, I am using the develop branch and if I tap on the exit button, the memory seems to go down again (even though not entirely back to normal as you will see if you take a lot of pictures as the percent of memory use slowly grows) but pretty much, yes. 
My guess is that if we solve the problem with the views the rest will probably be solved, too.

**Comment by blurtime** [comment]
But I was thinking it's easier to solve this altogether by removing strong references from the views that are retained. And I'm very close to removing all strong references. There is one remaining, though, from VideoPlayerView to avPlayerLayer:
<img width="1236" alt="Screenshot 2019-07-25 at 15 35 35" src="https://user-images.githubusercontent.com/29407428/61878757-e0993880-aef1-11e9-9eb4-a3631bb2cdb7.png">

**Comment by eonist** [comment]
Sure. feel free to solve them. It might fix the vid mem leak problem you are experiencing. Things always slowly build up. And then randomly go down. Create enough views and it will crash. In the 1000s etc.

**Comment by eonist** [comment]
You can also try to set things to `unowned self` not just weak self. There is a subtle difference.

**Comment by blurtime** [comment]
Rewrote the avPlayer and layer such that they are optional now, then set them to nil. Setting them to nil and removing the layer from the superlayer did solve the build-up 🎉 I'm sorry for this huge fuss but I really thought solving the view problem immediately would be easier - which it apparently isn't 😔Seriously sorry 

Moreover, my guess that removing all strong references would also solve the view problem doesn't seem to be right. There are none anymore, yet the views still build up. :/

**Comment by blurtime** [comment]
I don't have the build-up anymore but now I have the craziest retain cycle I have ever seen in my life: 
<img width="1440" alt="Screenshot 2019-07-25 at 15 51 23" src="https://user-images.githubusercontent.com/29407428/61879844-1dfec580-aef4-11e9-99ed-dcbc59e2d32c.png">

**Comment by eonist** [comment]
- `Rewrote the avPlayer and layer such that they are optional now` 👍
- Views in callbacks will retain. This code is meant as a start kit. Its meant to be tweaked and ironed out over time. Thats why its opensource. Im sure we can fix the view retain problem with some weak selfs and guards. There are a lot of callback nesting etc. You can try to to it. And then if you don't solve it fully, I can try to give it a go tonight. 
- Nice ring

**Comment by eonist** [comment]
- I usually pseudo code first
- Then make a fast prototype 
- Then tweak it , and fix issues. 

I never write perfect code from day 1. People that think they do that always creates a huge pile of perfect spagethi code.

**Comment by blurtime** [comment]
That's probably better. I tend to be too much of a perfectionist sometimes. As you can see I still have a lot to learn... The ring (although looking very nice) seems to be caused by some layers and I believe it is somehow related to the avPlayerLayer but I could be wrong since the views are also retained if I take photos. Here an example of me taking three videos and then 3 photos and canceling all of them): 
<img width="1440" alt="Screenshot 2019-07-25 at 16 03 58" src="https://user-images.githubusercontent.com/29407428/61880992-31129500-aef6-11e9-92b4-2b65f9a01fb8.png">

I tried so many things now but couldn't solve this issue by solving the views-problem... Would appreciate if you could look into it tonight and maybe already merge those changes to optional values into the `develop`, too. I have to leave for today :/ Worked a couple of hours now to find this problem. I hope you can somehow find and solve it 🙏😅
Thank you for still being so patient with me!

**Comment by eonist** [comment]
Your making progress. Shouldn't be much left now. Good luck on your test.

**Comment by eonist** [comment]
I can't see any commits to look into.

**Comment by blurtime** [comment]
Sorry, I didn't have any time yesterday. Like I said in a previous comment, all my attempts to solve the issue regarding the views being retained failed. Even though I removed some strong references those extraordinarily looking retain cycles still occurred. 
I thought you could try it on your phone again by recording and canceling a couple of times (engendering the build-up of views) and then debug the memory graph (as in this [answer on SO with malloc stack on](https://stackoverflow.com/questions/30992338/how-to-debug-memory-leaks-when-leaks-instrument-does-not-show-them/30993476?source=post_page---------------------------#30993476)) to see if you can identify the cause. I tried for 4-5 h and couldn't find a solution which removed the views :/

**Comment by eonist** [comment]
Ok. I can give it a go. Tonight

**Comment by blurtime** [comment]
You probably don't need to watch this but this guy explains very well and maybe we've been overlooking something he mentions in this video(?): [Memory 4 - Fixing Common Memory Problems: Reusable Popups (iOS, Xcode 9, Swift 4)](https://www.youtube.com/watch?v=h5c3MDbgn-c)

**Comment by eonist** [comment]
I fixed some obvious retain cycle things. But this code isn't meant to be a production ready framework. The UI code is suppose to be replaced with the UI code you want to use. Making sure all views are reallocated in the review views etc is a bit out of scope for this framework, as everyone has their own needs when it comes to presenting the video etc. 

Its fine for now. But at some point the library can't deallocate every single little view. When you use an app. Memory builds up. And then goes down. In the video I made now I made 10s of videos with various lengths. took pictures etc. I don't think 2mb memory increase in a camera app is a problem. iPhone 6 has 650mb available memory for an app before it crashes. You would have to make 4000 videos before it crashes. 

https://vimeo.com/350453573

**Comment by blurtime** [comment]
Alright, thank you really so much for helping out and especially for being so patient with me! You probably have a lot to do and thanks for taking the time. As I said before I tend to be or rather try to be too much of a perfectionist sometimes and it's a quality I guess I have to get rid of to a certain extent in order to ever finish my work. 

The reason why I was trying to perfect the UI code is that I wanted to use it as a base for my project but you are probably right when saying that recording up to 4000 videos without any obvious issues occurring is all we want.

**Comment by eonist** [comment]
Yes. The perfectionist will engulf us if we over focus on little things that has no meaning in the big picture Get to MVP. Then refine and perfect the code once you start testing in beta etc. I will help you out with PR reviews etc once your at that stage. But we are not there yet. ;)
